.PHONY: protos

protos:
	# protoc -I protos/ protos/currency.proto --go_out=protos/currency --go_opt=paths=source_relative --go-grpc_out=protos/currency --go-grpc_opt=paths=source_relative,require_unimplemented_servers=false
	protoc -I protos/ protos/currency.proto --go_out=protos/currency --go_opt=paths=source_relative --go-grpc_out=protos/currency --go-grpc_opt=paths=source_relative


